import { Router, Request, Response } from 'express';
import mongoose from 'mongoose';
import { Appointment } from '../models/Appointment';
import { User } from '../models/User';
import { MoneySlip } from '../models/MoneySlip';
import { getMongoConnectedStatus } from '../config/db';

const router = Router();

let inMemoryAppointments: any[] = [
  {
    id: 'APP-001',
    patientName: 'محمد طارق',
    phone: '03001234567',
    city: 'گوجرانوالہ',
    problem: 'کمر و مہروں کا شدید درد',
    doctorName: 'ڈاکٹر زیشان چوہدری (MBBS)',
    date: new Date().toISOString().split('T')[0],
    timeSlot: 'صبح 10:00 - 11:00',
    status: 'Approved',
    tokenNumber: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'APP-002',
    patientName: 'کامران علی',
    phone: '03219876543',
    city: 'لاہور',
    problem: 'فالج بحالی فزیوتھراپی',
    doctorName: 'ڈاکٹر وقاص صغیر چوہدری (MBBS)',
    date: new Date().toISOString().split('T')[0],
    timeSlot: 'دوپہر 02:00 - 03:00',
    status: 'Pending',
    tokenNumber: 2,
    createdAt: new Date().toISOString(),
  },
];

let apptSeqCount = 10;
function generateSequentialAppointmentId() {
  apptSeqCount += 1;
  const num = String(apptSeqCount).padStart(3, '0');
  return `APP-${num}`;
}

// Auto generate OPD Money Slip for an approved appointment
async function autoCreateAppointmentSlip(appt: any) {
  try {
    const apptId = appt.id || (appt._id ? String(appt._id) : `APP-${Date.now()}`);
    const fee = 1500;
    const cleanPhone = (appt.phone || '').replace(/\D/g, '');
    const mrnNumber = `MRN-${cleanPhone.slice(-4) || '1001'}`;

    if (getMongoConnectedStatus()) {
      const existing = await MoneySlip.findOne({ appointmentId: apptId });
      if (!existing) {
        await MoneySlip.create({
          slipNo: `SLIP-OPD-${Math.floor(1000 + Math.random() * 9000)}`,
          patientName: appt.patientName,
          patientPhone: appt.phone || '',
          mrnNumber,
          doctorName: appt.doctorName || 'ڈاکٹر زیشان چوہدری (MBBS)',
          date: appt.date || new Date().toISOString().split('T')[0],
          items: [
            {
              id: `item-opd-${Date.now()}`,
              description: `ڈاکٹر معائنہ و چیک اپ فیس (${appt.doctorName || 'Senior Consultant'})`,
              category: 'Checkup Fee',
              quantity: 1,
              unitPrice: fee,
              totalPrice: fee,
            },
          ],
          subtotal: fee,
          discount: 0,
          totalAmount: fee,
          paidAmount: 0,
          balanceAmount: fee,
          paymentStatus: 'Unpaid',
          paymentMethod: 'Cash',
          notes: `او پی ڈی ٹوکن نمبر #${appt.tokenNumber || 1} برائے ${appt.problem || 'معائنہ'}`,
          appointmentId: apptId,
          isAutoGenerated: true,
          source: 'Appointment',
        });
      }
    }
  } catch (e) {
    // Non-blocking background slip creation
  }
}

// GET /api/appointments
router.get('/', async (req: Request, res: Response) => {
  try {
    const { doctorName, date, phone, status } = req.query;

    if (getMongoConnectedStatus()) {
      const filter: any = {};
      if (doctorName) filter.doctorName = new RegExp(String(doctorName), 'i');
      if (date) filter.date = String(date);
      if (phone) filter.phone = new RegExp(String(phone), 'i');
      if (status) filter.status = String(status);

      let dbList: any[] = await Appointment.find(filter).sort({ createdAt: -1 });

      // Auto-sync registered patient users from MongoDB Atlas into appointments if empty
      if (!doctorName && !date && !phone && !status) {
        const mongoPatients = await User.find({ role: 'patient' }).sort({ createdAt: -1 });
        for (const u of mongoPatients) {
          const uId = u._id.toString();
          const uName = u.name || u.username;
          const uPhone = u.phone;
          const alreadyInList = dbList.some((a) =>
            (a.patientId && String(a.patientId) === uId) ||
            (a.patientName && uName && a.patientName.toLowerCase() === uName.toLowerCase()) ||
            (uPhone && a.phone && uPhone === a.phone)
          );
          if (!alreadyInList) {
            const autoAppt = {
              id: `APP-P${uId.slice(-4)}`,
              patientId: uId,
              patientName: uName,
              phone: uPhone || '03000000000',
              city: u.city || 'گوجرانوالہ',
              problem: 'رجسٹرڈ بیمار (OPD Checkup)',
              doctorName: 'ڈاکٹر زیشان چوہدری (MBBS)',
              date: new Date(u.createdAt || Date.now()).toISOString().split('T')[0],
              timeSlot: 'صبح 10:00 - 01:00',
              status: 'Pending',
              tokenNumber: dbList.length + 1,
              createdAt: u.createdAt || new Date().toISOString(),
            };
            const createdAppt = await Appointment.create(autoAppt).catch(() => null);
            if (createdAppt) {
              dbList.unshift(createdAppt);
            }
          }
        }
      }
      return res.json({ success: true, appointments: dbList });
    }

    let filtered = [...inMemoryAppointments];
    if (doctorName) filtered = filtered.filter((a) => a.doctorName && a.doctorName.toLowerCase().includes(String(doctorName).toLowerCase()));
    if (date) filtered = filtered.filter((a) => a.date === String(date));
    if (phone) filtered = filtered.filter((a) => a.phone && a.phone.includes(String(phone)));
    if (status) filtered = filtered.filter((a) => a.status === String(status));

    return res.json({ success: true, appointments: filtered });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message, appointments: inMemoryAppointments });
  }
});

// POST /api/appointments
router.post('/', async (req: Request, res: Response) => {
  try {
    let apptId = req.body.id;
    if (!apptId || !apptId.startsWith('APP-')) {
      apptId = generateSequentialAppointmentId();
    }

    const todayStr = req.body.date || new Date().toISOString().split('T')[0];
    const todayCount = inMemoryAppointments.filter((a) => a.date === todayStr).length;
    const tokenNumber = req.body.tokenNumber || (todayCount + 1);

    const apptObj = {
      ...req.body,
      id: apptId,
      date: todayStr,
      tokenNumber,
      status: req.body.status || 'Pending',
      createdAt: req.body.createdAt || new Date().toISOString(),
    };

    inMemoryAppointments.unshift(apptObj);

    if (getMongoConnectedStatus()) {
      await Appointment.create(apptObj).catch(() => {});
      if (apptObj.status === 'Approved') {
        await autoCreateAppointmentSlip(apptObj);
      }
    }

    return res.status(201).json({ success: true, appointment: apptObj });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// PUT /api/appointments/:id
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    let updatedAppt: any = null;

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { id: id }] } : { id: id };
      updatedAppt = await Appointment.findOneAndUpdate(
        query,
        { $set: req.body },
        { returnDocument: 'after' }
      );

      if (updatedAppt && (req.body.status === 'Approved' || updatedAppt.status === 'Approved')) {
        await autoCreateAppointmentSlip(updatedAppt);
      }
    }

    const index = inMemoryAppointments.findIndex((a) => a.id === id || (a._id && String(a._id) === id));
    if (index !== -1) {
      inMemoryAppointments[index] = { ...inMemoryAppointments[index], ...req.body };
      if (!updatedAppt) updatedAppt = inMemoryAppointments[index];
    } else {
      inMemoryAppointments.unshift({ id, ...req.body });
      if (!updatedAppt) updatedAppt = { id, ...req.body };
    }

    return res.json({ success: true, appointment: updatedAppt });
  } catch (err: any) {
    console.error('Error updating appointment:', err);
    return res.status(500).json({ success: false, message: err.message });
  }
});

// DELETE /api/appointments/:id
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    inMemoryAppointments = inMemoryAppointments.filter((a) => a.id !== id && (!a._id || String(a._id) !== id));

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { id: id }] } : { id: id };
      await Appointment.findOneAndDelete(query).catch(() => {});
    }

    return res.json({ success: true, message: 'Appointment deleted successfully.' });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
