import { Router, Request, Response } from 'express';
import mongoose from 'mongoose';
import { Order } from '../models/Order';
import { Product } from '../models/Product';
import { MoneySlip } from '../models/MoneySlip';
import { getMongoConnectedStatus } from '../config/db';

const router = Router();

let inMemoryOrders: any[] = [];

// Helper function to safely adjust product stock
async function adjustProductStock(items: any[], isReversal = false) {
  if (!items || !Array.isArray(items) || !getMongoConnectedStatus()) return;
  for (const item of items) {
    const qty = Number(item.quantity || 1);
    const multiplier = isReversal ? 1 : -1;
    const delta = multiplier * qty;

    if (item.productId && mongoose.Types.ObjectId.isValid(item.productId)) {
      await Product.findByIdAndUpdate(item.productId, { $inc: { stock: delta } }).catch(() => {});
    } else if (item.productName) {
      await Product.findOneAndUpdate(
        {
          $or: [
            { nameEnglish: new RegExp(item.productName.trim(), 'i') },
            { nameUrdu: new RegExp(item.productName.trim(), 'i') },
          ],
        },
        { $inc: { stock: delta } }
      ).catch(() => {});
    }
  }
}

// GET /api/orders
router.get('/', async (req: Request, res: Response) => {
  try {
    const { phone, trackingId, status } = req.query;

    if (getMongoConnectedStatus()) {
      const filter: any = {};
      if (phone) filter.phone = new RegExp(String(phone), 'i');
      if (trackingId) filter.trackingId = new RegExp(String(trackingId), 'i');
      if (status) filter.status = String(status);

      const orders = await Order.find(filter).sort({ createdAt: -1 });
      return res.json({ success: true, orders });
    }

    let filtered = [...inMemoryOrders];
    if (phone) filtered = filtered.filter((o) => o.phone && o.phone.includes(String(phone)));
    if (trackingId) filtered = filtered.filter((o) => o.trackingId && o.trackingId.includes(String(trackingId)));
    if (status) filtered = filtered.filter((o) => o.status === String(status));

    return res.json({ success: true, orders: filtered });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message, orders: inMemoryOrders });
  }
});

// POST /api/orders
router.post('/', async (req: Request, res: Response) => {
  try {
    const trackingId = req.body.trackingId || `TRK-${Math.floor(100000 + Math.random() * 900000)}`;
    const items = req.body.items || [];
    const totalPricePKR = Number(req.body.totalPricePKR) || 0;

    const orderData = {
      ...req.body,
      items,
      totalPricePKR,
      trackingId,
      status: req.body.status || 'Processing',
      date: req.body.date || new Date().toISOString().split('T')[0],
      createdAt: req.body.createdAt || new Date().toISOString(),
    };

    let createdOrder: any = null;

    if (getMongoConnectedStatus()) {
      createdOrder = await Order.create(orderData);
      // Automated Inventory Depletion
      await adjustProductStock(items, false);

      // Auto-generate pharmacy/store money slip for clinical records
      const slipItems = items.map((it: any, idx: number) => ({
        id: `item-ord-${idx + 1}`,
        description: it.productName || 'ہربل میڈیسن',
        category: 'Medicine',
        quantity: Number(it.quantity || 1),
        unitPrice: Number(it.pricePKR || 0),
        totalPrice: Number(it.pricePKR || 0) * Number(it.quantity || 1),
      }));

      if (slipItems.length > 0) {
        await MoneySlip.create({
          slipNo: `SLIP-ORD-${trackingId.slice(-4)}`,
          patientName: req.body.customerName || 'آن لائن گاہک',
          patientPhone: req.body.phone || '',
          doctorName: 'آن لائن فارمیسی / اسٹور',
          date: new Date().toISOString().split('T')[0],
          items: slipItems,
          subtotal: totalPricePKR,
          discount: 0,
          totalAmount: totalPricePKR,
          paidAmount: req.body.paymentMethod === 'Online' ? totalPricePKR : 0,
          balanceAmount: req.body.paymentMethod === 'Online' ? 0 : totalPricePKR,
          paymentStatus: req.body.paymentMethod === 'Online' ? 'Paid' : 'Unpaid',
          paymentMethod: req.body.paymentMethod || 'Cash',
          notes: `آن لائن آرڈر ٹریکنگ: ${trackingId} - پتہ: ${req.body.address || ''}, ${req.body.city || ''}`,
          isAutoGenerated: true,
          source: 'Store Order',
        }).catch(() => {});
      }
    } else {
      createdOrder = { id: `ord_${Date.now()}`, ...orderData };
    }

    inMemoryOrders.unshift(createdOrder);
    return res.status(201).json({ success: true, order: createdOrder });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// PUT /api/orders/:id
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    let updatedOrder: any = null;

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { trackingId: id }] } : { trackingId: id };
      const currentOrder = await Order.findOne(query);

      // If status changed to Cancelled, restore stock
      if (currentOrder && currentOrder.status !== 'Cancelled' && req.body.status === 'Cancelled') {
        await adjustProductStock(currentOrder.items, true);
      }

      updatedOrder = await Order.findOneAndUpdate(query, { $set: req.body }, { returnDocument: 'after' });
    }

    const idx = inMemoryOrders.findIndex((o) => o._id === id || o.id === id || o.trackingId === id);
    if (idx !== -1) {
      inMemoryOrders[idx] = { ...inMemoryOrders[idx], ...req.body };
      if (!updatedOrder) updatedOrder = inMemoryOrders[idx];
    }

    return res.json({ success: true, order: updatedOrder || { id, ...req.body } });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// DELETE /api/orders/:id
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { trackingId: id }] } : { trackingId: id };
      const currentOrder = await Order.findOne(query);

      // Restore stock if not already cancelled
      if (currentOrder && currentOrder.status !== 'Cancelled') {
        await adjustProductStock(currentOrder.items, true);
      }

      await Order.findOneAndDelete(query);
    }

    inMemoryOrders = inMemoryOrders.filter((o) => o._id !== id && o.id !== id && o.trackingId !== id);
    return res.json({ success: true, message: 'Order deleted and inventory restored successfully.' });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
