import { Router, Request, Response } from 'express';
import mongoose from 'mongoose';
import { MoneySlip } from '../models/MoneySlip';
import { Doctor } from '../models/Doctor';
import { Product } from '../models/Product';
import { getMongoConnectedStatus } from '../config/db';

const router = Router();

let inMemorySlips: any[] = [
  {
    id: 'slip-1001',
    slipNo: 'SLIP-1001',
    patientName: 'محمد طارق (Tariq)',
    patientPhone: '03001234567',
    mrnNumber: 'MRN-4589',
    doctorName: 'ڈاکٹر زیشان چوہدری (MBBS)',
    date: new Date().toISOString().split('T')[0],
    items: [
      { id: 'item-1', description: 'ڈاکٹر معائنہ و چیک اپ فیس (OPD Checkup)', category: 'Checkup Fee', quantity: 1, unitPrice: 1500, totalPrice: 1500 },
      { id: 'item-2', description: 'هوراب ہیئر آئل (Hoorab Hair Oil 200ml)', category: 'Medicine', quantity: 2, unitPrice: 1650, totalPrice: 3300 },
      { id: 'item-3', description: 'کمپیوٹرائزڈ بائیو کوانٹم باڈی اسکین', category: 'Lab Test / Scan', quantity: 1, unitPrice: 1500, totalPrice: 1500 },
    ],
    subtotal: 6300,
    discount: 300,
    totalAmount: 6000,
    paidAmount: 6000,
    balanceAmount: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    notes: 'مکمل ادائیگی نقد وصول کر لی گئی۔',
    appointmentId: 'APP-001',
    isAutoGenerated: true,
    source: 'Appointment',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slip-1002',
    slipNo: 'SLIP-1002',
    patientName: 'کامران علی (Kamran Ali)',
    patientPhone: '03219876543',
    mrnNumber: 'MRN-6520',
    doctorName: 'ڈاکٹر وقاص صغیر چوہدری (MBBS)',
    date: new Date().toISOString().split('T')[0],
    items: [
      { id: 'item-1', description: 'فزیو تھراپی کنسلٹیشن فیس', category: 'Checkup Fee', quantity: 1, unitPrice: 2000, totalPrice: 2000 },
      { id: 'item-2', description: 'مہرے سیدھا کرنے کا سیشن (Spine Decompression)', category: 'Physiotherapy', quantity: 2, unitPrice: 2500, totalPrice: 5000 },
      { id: 'item-3', description: 'درد کشا مرہم اور نرو ٹانک', category: 'Medicine', quantity: 1, unitPrice: 2500, totalPrice: 2500 },
    ],
    subtotal: 9500,
    discount: 1000,
    totalAmount: 8500,
    paidAmount: 5000,
    balanceAmount: 3500,
    paymentStatus: 'Partial',
    paymentMethod: 'EasyPaisa',
    notes: 'بقایا جات 3,500 روپے اگلے سیشن پر واجب الادا ہیں۔',
    appointmentId: 'APP-002',
    isAutoGenerated: true,
    source: 'Appointment',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'slip-1003',
    slipNo: 'SLIP-1003',
    patientName: 'زینب بی بی (Zainab Bibi)',
    patientPhone: '03221122334',
    mrnNumber: 'MRN-99110',
    doctorName: 'ڈاکٹر زیشان چوہدری',
    date: new Date().toISOString().split('T')[0],
    items: [
      { id: 'item-1', description: 'کمپیوٹرائزڈ نظر کا چشمہ و فریم (Anti-Glare Optical Lens)', category: 'Eye Care / Glasses', quantity: 1, unitPrice: 3500, totalPrice: 3500 },
      { id: 'item-2', description: 'کولنگ ہربل آئی ڈراپس', category: 'Eye Care / Glasses', quantity: 1, unitPrice: 650, totalPrice: 650 },
    ],
    subtotal: 4150,
    discount: 150,
    totalAmount: 4000,
    paidAmount: 4000,
    balanceAmount: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    notes: 'نظر کا فریم اور لینس ڈیلیور کر دیا گیا۔',
    isAutoGenerated: false,
    source: 'Doctor OPD',
    createdAt: new Date().toISOString(),
  },
];

let slipSeqCount = 1003;
function generateSequentialSlipNumber() {
  slipSeqCount += 1;
  return `SLIP-${slipSeqCount}`;
}

// Deduct inventory when medicine items are invoiced
async function deductMedicineStock(items: any[]) {
  if (!items || !Array.isArray(items) || !getMongoConnectedStatus()) return;
  for (const it of items) {
    if (it.category === 'Medicine' && it.description) {
      const qty = Number(it.quantity || 1);
      const cleanDesc = it.description.split('(')[0].trim();
      await Product.findOneAndUpdate(
        {
          $or: [
            { nameUrdu: new RegExp(cleanDesc, 'i') },
            { nameEnglish: new RegExp(cleanDesc, 'i') },
          ],
        },
        { $inc: { stock: -qty } }
      ).catch(() => {});
    }
  }
}

// GET /api/slips/analytics - Automated Clinical Financial Overview
router.get('/analytics', async (req: Request, res: Response) => {
  try {
    let slips: any[] = inMemorySlips;
    if (getMongoConnectedStatus()) {
      slips = await MoneySlip.find().sort({ createdAt: -1 });
    }

    const todayStr = new Date().toISOString().split('T')[0];
    const thisMonthStr = todayStr.slice(0, 7); // YYYY-MM

    let totalRevenue = 0;
    let totalPaid = 0;
    let totalBalance = 0;
    let totalDiscount = 0;
    let todayRevenue = 0;
    let todayPaid = 0;
    let monthRevenue = 0;
    let monthPaid = 0;

    const paymentMethodsBreakdown: Record<string, number> = {
      Cash: 0,
      EasyPaisa: 0,
      JazzCash: 0,
      Card: 0,
      'Bank Transfer': 0,
    };

    const categoryBreakdown: Record<string, number> = {
      'Checkup Fee': 0,
      Medicine: 0,
      'Lab Test / Scan': 0,
      Physiotherapy: 0,
      'Eye Care / Glasses': 0,
      Other: 0,
    };

    slips.forEach((s) => {
      const total = Number(s.totalAmount || 0);
      const paid = Number(s.paidAmount || 0);
      const balance = Number(s.balanceAmount || 0);
      const discount = Number(s.discount || 0);
      const date = s.date || '';

      totalRevenue += total;
      totalPaid += paid;
      totalBalance += balance;
      totalDiscount += discount;

      if (date === todayStr) {
        todayRevenue += total;
        todayPaid += paid;
      }
      if (date.startsWith(thisMonthStr)) {
        monthRevenue += total;
        monthPaid += paid;
      }

      const method = s.paymentMethod || 'Cash';
      paymentMethodsBreakdown[method] = (paymentMethodsBreakdown[method] || 0) + paid;

      (s.items || []).forEach((it: any) => {
        const cat = it.category || 'Other';
        const itemTotal = Number(it.totalPrice || (it.unitPrice || 0) * (it.quantity || 1));
        categoryBreakdown[cat] = (categoryBreakdown[cat] || 0) + itemTotal;
      });
    });

    return res.json({
      success: true,
      analytics: {
        totalSlipsCount: slips.length,
        totalRevenue,
        totalPaid,
        totalBalance,
        totalDiscount,
        todayRevenue,
        todayPaid,
        monthRevenue,
        monthPaid,
        paymentMethodsBreakdown,
        categoryBreakdown,
        collectionRatePercentage: totalRevenue > 0 ? Math.round((totalPaid / totalRevenue) * 100) : 100,
      },
    });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// GET /api/slips
router.get('/', async (req: Request, res: Response) => {
  try {
    const { phone, mrn, patientId, doctorName, appointmentId, tokenNumber, q } = req.query;

    if (getMongoConnectedStatus()) {
      const filter: any = {};
      if (phone) filter.patientPhone = new RegExp(String(phone), 'i');
      if (mrn) filter.mrnNumber = new RegExp(String(mrn), 'i');
      if (doctorName) filter.doctorName = new RegExp(String(doctorName), 'i');
      if (appointmentId) filter.appointmentId = String(appointmentId);
      if (tokenNumber) {
        filter.$or = [
          { tokenNumber: String(tokenNumber) },
          { tokenNumber: Number(tokenNumber) },
          { slipNo: new RegExp(String(tokenNumber), 'i') }
        ];
      }
      if (q) {
        const queryRegex = new RegExp(String(q), 'i');
        filter.$or = [
          { patientName: queryRegex },
          { patientPhone: queryRegex },
          { mrnNumber: queryRegex },
          { slipNo: queryRegex },
          { tokenNumber: queryRegex },
        ];
      }

      const dbSlips = await MoneySlip.find(filter).sort({ createdAt: -1 });
      if (dbSlips.length > 0) {
        return res.json({ success: true, slips: dbSlips });
      }
    }

    let filtered = [...inMemorySlips];
    if (phone) {
      filtered = filtered.filter((s) => s.patientPhone && s.patientPhone.includes(String(phone)));
    }
    if (mrn) {
      filtered = filtered.filter((s) => s.mrnNumber && s.mrnNumber.toLowerCase().includes(String(mrn).toLowerCase()));
    }
    if (doctorName) {
      filtered = filtered.filter((s) => s.doctorName && s.doctorName.toLowerCase().includes(String(doctorName).toLowerCase()));
    }
    if (appointmentId) {
      filtered = filtered.filter((s) => s.appointmentId === String(appointmentId));
    }
    if (tokenNumber) {
      filtered = filtered.filter(
        (s) =>
          String(s.tokenNumber || '') === String(tokenNumber) ||
          String(s.slipNo || '').toLowerCase().includes(String(tokenNumber).toLowerCase())
      );
    }
    if (q) {
      const term = String(q).toLowerCase();
      filtered = filtered.filter(
        (s) =>
          (s.patientName || '').toLowerCase().includes(term) ||
          (s.patientPhone || '').includes(term) ||
          (s.mrnNumber || '').toLowerCase().includes(term) ||
          (s.slipNo || '').toLowerCase().includes(term) ||
          String(s.tokenNumber || '').toLowerCase().includes(term)
      );
    }

    return res.json({ success: true, slips: filtered });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message, slips: inMemorySlips });
  }
});

// POST /api/slips
router.post('/', async (req: Request, res: Response) => {
  try {
    let slipNo = req.body.slipNo;
    if (!slipNo || !slipNo.startsWith('SLIP-')) {
      slipNo = generateSequentialSlipNumber();
    }

    const items = req.body.items || [];
    const subtotal = items.reduce((sum: number, it: any) => sum + (Number(it.quantity || 1) * Number(it.unitPrice || 0)), 0);
    const discount = Number(req.body.discount) || 0;
    const totalAmount = Math.max(0, subtotal - discount);
    const paidAmount = Number(req.body.paidAmount) || 0;
    const balanceAmount = Math.max(0, totalAmount - paidAmount);

    let paymentStatus: 'Paid' | 'Partial' | 'Unpaid' = 'Unpaid';
    if (paidAmount >= totalAmount && totalAmount > 0) {
      paymentStatus = 'Paid';
    } else if (paidAmount > 0) {
      paymentStatus = 'Partial';
    }

    const newSlip = {
      ...req.body,
      id: req.body.id || `slip-${Date.now()}`,
      slipNo,
      items,
      subtotal,
      discount,
      totalAmount,
      paidAmount,
      balanceAmount,
      paymentStatus: req.body.paymentStatus || paymentStatus,
      paymentMethod: req.body.paymentMethod || 'Cash',
      date: req.body.date || new Date().toISOString().split('T')[0],
      createdAt: req.body.createdAt || new Date().toISOString(),
    };

    inMemorySlips.unshift(newSlip);

    if (getMongoConnectedStatus()) {
      await MoneySlip.create(newSlip).catch(() => {});
      await deductMedicineStock(items);
    }

    return res.status(201).json({ success: true, slip: newSlip });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// POST /api/slips/auto-appointment
// Triggers automatic invoice generation when an appointment is approved
router.post('/auto-appointment', async (req: Request, res: Response) => {
  try {
    const { appointmentId, patientName, patientPhone, doctorName, checkupFee, city, problem, tokenNumber } = req.body;

    if (!patientName) {
      return res.status(400).json({ success: false, message: 'Patient name is required' });
    }

    // Check if invoice already exists for this appointment
    const existingIndex = inMemorySlips.findIndex((s) => s.appointmentId === appointmentId);
    const fee = Number(checkupFee) > 0 ? Number(checkupFee) : 1500;

    if (existingIndex !== -1) {
      // If tokenNumber is passed, ensure it is updated
      if (tokenNumber && !inMemorySlips[existingIndex].tokenNumber) {
        inMemorySlips[existingIndex].tokenNumber = tokenNumber;
      }
      return res.json({ success: true, slip: inMemorySlips[existingIndex], alreadyExists: true });
    }

    const slipNo = generateSequentialSlipNumber();
    const cleanPhone = (patientPhone || '').replace(/\D/g, '');
    const mrnNumber = `MRN-${cleanPhone.slice(-4) || '1001'}`;
    const tokenDisplay = tokenNumber ? ` (ٹوکن #${tokenNumber})` : '';

    const items = [
      {
        id: `it-${Date.now()}-1`,
        description: `ڈاکٹر معائنہ و چیک اپ فیس (${doctorName || 'Senior Consultant'})${tokenDisplay}`,
        category: 'Checkup Fee',
        quantity: 1,
        unitPrice: fee,
        totalPrice: fee,
        department: 'OPD / Doctor Checkup',
        servedBy: doctorName || 'Senior Doctor',
      },
    ];

    const newSlip = {
      id: `slip-${Date.now()}`,
      slipNo,
      tokenNumber: tokenNumber || (appointmentId ? `TK-${appointmentId.replace('APP-', '')}` : 'TK-101'),
      patientName,
      patientPhone: patientPhone || '',
      mrnNumber,
      doctorName: doctorName || 'ڈاکٹر زیشان چوہدری',
      date: new Date().toISOString().split('T')[0],
      items,
      subtotal: fee,
      discount: 0,
      totalAmount: fee,
      paidAmount: 0,
      balanceAmount: fee,
      paymentStatus: 'Unpaid',
      paymentMethod: 'Cash',
      notes: `خودکار اپائنٹمنٹ بل برائے ${problem || 'او پی ڈی معائنہ'} ${tokenDisplay}`,
      appointmentId,
      isAutoGenerated: true,
      source: 'Appointment',
      createdAt: new Date().toISOString(),
    };

    inMemorySlips.unshift(newSlip);

    if (getMongoConnectedStatus()) {
      await MoneySlip.create(newSlip).catch(() => {});
    }

    return res.status(201).json({ success: true, slip: newSlip });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// PUT /api/slips/:id
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    let updatedSlip: any = null;

    const items = req.body.items;
    let computedFields: any = {};
    if (items && Array.isArray(items)) {
      const subtotal = items.reduce((sum: number, it: any) => sum + (Number(it.quantity || 1) * Number(it.unitPrice || 0)), 0);
      const discount = Number(req.body.discount !== undefined ? req.body.discount : 0);
      const totalAmount = Math.max(0, subtotal - discount);
      const paidAmount = Number(req.body.paidAmount !== undefined ? req.body.paidAmount : 0);
      const balanceAmount = Math.max(0, totalAmount - paidAmount);

      let paymentStatus = req.body.paymentStatus;
      if (!paymentStatus) {
        if (paidAmount >= totalAmount && totalAmount > 0) paymentStatus = 'Paid';
        else if (paidAmount > 0) paymentStatus = 'Partial';
        else paymentStatus = 'Unpaid';
      }

      computedFields = { subtotal, discount, totalAmount, paidAmount, balanceAmount, paymentStatus };
    }

    const payload = { ...req.body, ...computedFields };

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { id: id }, { slipNo: id }] } : { $or: [{ id: id }, { slipNo: id }] };
      updatedSlip = await MoneySlip.findOneAndUpdate(query, { $set: payload }, { returnDocument: 'after' });
    }

    const index = inMemorySlips.findIndex((s) => s.id === id || s.slipNo === id || (s._id && String(s._id) === id));
    if (index !== -1) {
      inMemorySlips[index] = { ...inMemorySlips[index], ...payload };
      if (!updatedSlip) updatedSlip = inMemorySlips[index];
    } else {
      inMemorySlips.unshift({ id, ...payload });
      if (!updatedSlip) updatedSlip = { id, ...payload };
    }

    return res.json({ success: true, slip: updatedSlip });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// DELETE /api/slips/:id
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    inMemorySlips = inMemorySlips.filter((s) => s.id !== id && s.slipNo !== id && (!s._id || String(s._id) !== id));

    if (getMongoConnectedStatus()) {
      const isObjId = mongoose.Types.ObjectId.isValid(id);
      const query = isObjId ? { $or: [{ _id: id }, { id: id }, { slipNo: id }] } : { $or: [{ id: id }, { slipNo: id }] };
      await MoneySlip.findOneAndDelete(query).catch(() => {});
    }

    return res.json({ success: true, message: 'Money slip deleted successfully' });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
