import mongoose from 'mongoose';

export interface IMoneySlipItem {
  id: string;
  description: string;
  category: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  department?: string;
  servedBy?: string;
}

export interface IMoneySlip extends mongoose.Document {
  id?: string;
  slipNo: string;
  tokenNumber?: number | string;
  patientName: string;
  patientPhone: string;
  mrnNumber?: string;
  doctorName: string;
  date: string;
  items: IMoneySlipItem[];
  subtotal: number;
  discount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  paymentStatus: 'Paid' | 'Partial' | 'Unpaid';
  paymentMethod: 'Cash' | 'Card' | 'EasyPaisa' | 'JazzCash' | 'Bank Transfer';
  notes?: string;
  appointmentId?: string;
  isAutoGenerated?: boolean;
  source?: string;
  referralInfo?: string;
  createdAt?: Date;
}

const MoneySlipSchema = new mongoose.Schema({
  id: { type: String, index: true },
  slipNo: { type: String, required: true, index: true },
  tokenNumber: { type: mongoose.Schema.Types.Mixed, index: true },
  patientName: { type: String, required: true },
  patientPhone: { type: String, required: true, index: true },
  mrnNumber: { type: String, index: true },
  doctorName: { type: String, required: true, index: true },
  date: { type: String, default: () => new Date().toISOString().split('T')[0], index: true },
  items: [
    {
      id: { type: String },
      description: { type: String, required: true },
      category: { type: String, default: 'Checkup Fee' },
      quantity: { type: Number, default: 1 },
      unitPrice: { type: Number, default: 0 },
      totalPrice: { type: Number, default: 0 },
    },
  ],
  subtotal: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  totalAmount: { type: Number, default: 0 },
  paidAmount: { type: Number, default: 0 },
  balanceAmount: { type: Number, default: 0 },
  paymentStatus: { type: String, default: 'Unpaid', index: true },
  paymentMethod: { type: String, default: 'Cash' },
  notes: { type: String },
  appointmentId: { type: String, index: true },
  isAutoGenerated: { type: Boolean, default: false },
  source: { type: String, default: 'Manual' },
  referralInfo: { type: String },
  createdAt: { type: Date, default: Date.now, index: true },
});

MoneySlipSchema.index({ patientPhone: 1, date: -1 });
MoneySlipSchema.index({ doctorName: 1, date: -1 });

export const MoneySlip: any = mongoose.models.MoneySlip || mongoose.model('MoneySlip', MoneySlipSchema);
